name: Update version + testing

on:
  push:
  pull_request:

jobs:
  archlinux:
    runs-on: ubuntu-latest
    container: martynas/archlinux
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: namcap
        run: |
          namcap PKGBUILD
