name: Update Version of Package
on:
  pull_request:
  push:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.12
        with:
          target: 'pkgbuild'
          pkgname: '.'

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: 2m/arch-pkgbuild-builder@v1.12
        with:
          target: 'srcinfo'
          pkgname: '.'

      - name: Validate binary
        id: validate-binary
        uses: 2m/arch-pkgbuild-builder@v1.12
        with:
          target: 'run'
          pkgname: '.'
          command: '1password --version'
